### ISSUE TITLE
Unicode replacements

### ISSUE THREAD

**Issue by Askaniy** [levinli303/astroweather-localization#10]
Suggest to replace
- `->` with `→` in `sky_chart_teaching_card_detail`
- `-` with `−` (minus sign) in `help_section_instruction5`
- `-` with `–` (en dash) in `help_section_instruction2`, `help_section_instruction7`, `widget_next_spacecraft_pass_time_range`
- `m2` with `m²` in `light_pollution_teaching_card_title_X`

Also, I thought `%%` is needed as escaped character, but I see this doubled percent on Android

**Comment by levinli303** [comment]
%% is probably for formatted string only. i don't think we have strings that contains percent signs which we need to format

**Comment by levinli303** [comment]
Fixed in https://github.com/levinli303/astroweather-localization/commit/4443b147e49865e4f4bbdd4a63c1965617e14d0f
