### ISSUE TITLE
Update translation in Russian

### ISSUE THREAD

**Issue by levinli303** [levinli303/astroweather-localization#3]
There are a few new strings, can you help translate them into Russian? @Askaniy 

<img width="913" alt="Screen Shot 2021-04-18 at 8 29 43 PM" src="https://user-images.githubusercontent.com/17924287/115145573-d1bec600-a084-11eb-9309-9418e27adfe6.png">

and in addition, this, as  I need to add to the about view:

Translators
Russian: Your Name

**Comment by Askaniy** [comment]
`Вы хотите добавить данное событие в календарь?`
`Событие Astroweather` if app is meant or `Событие астрономической погоды`
`Политика конфиденциальности и условия пользования`
`Политика конфиденциальности и условия пользования`
`Просим внимательно ознакомиться с политикой конфиденциальности и условиями пользования.`
`Принимаю`
`Напомнить позже`
`Ознакомиться с политикой конфиденциальности`
`Не удаётся добавить событие в календарь.`
`Пропустить`
`%d с`
`Закрыть`

`Переводчики`
`Русский`: Askaniy Anpilogov

**Comment by levinli303** [comment]
Updated in https://github.com/levinli303/astroweather-localization/commit/d7f74b104cce934f5cbdb2814548793b8863559f
