### ISSUE TITLE
Twilight naming

### ISSUE THREAD

**Issue by Askaniy** [levinli303/astroweather-localization#8]
Twilight confused me, unraveling:
Astronomical/Nautical/Civil _dawn_ ⇾ day ⇾ Civil/Nautical/Astronomical dusk ⇾ night
Currently, the app uses "twilight" instead of implied "dawn"
Solution 1: name and dawn, and dusk as "twilight"
Solution 2: rename twilight to dawn

Additionally, I suggest renaming `sun_position_astronomical_unknown`, `sun_position_nautical_unknown`, to "_ Twilight" instead of "_ Twilight/Dusk". There is no "night" period in my location right now, and astronomical midnight looks laggy.

**Comment by Askaniy** [comment]
Add. Info: In Russian, twilight does not have separate names for morning / evening, so with any solution everything will be translated as "twilight"

**Comment by levinli303** [comment]
i think using dawn/dusk is better.

Renaming sun_position_astronomical_unknown sun_position_nautical_unknown to xx Twilight also sounds good.

**Comment by levinli303** [comment]
done in https://github.com/levinli303/astroweather-localization/commit/0cb4d9a5cef86e9c72d8c9b5cdce74346034cf82
