### ISSUE TITLE
Azimuth in degrees

### ISSUE THREAD

**Issue by Askaniy** [levinli303/astroweather-localization#9]
Currently, the azimuth converted to the letter direction is used throughout the app. It might be convenient, but not for me...
Options:
1) Specify letters in brackets
2) Specify degrees in brackets
3) Add a setting with a choice (then there will definitely not be problems with lack of screen space)

**Comment by levinli303** [comment]
The rise/set screen will be updated to this:

<img width="379" alt="Screenshot 2023-07-31 at 22 30 41" src="https://github.com/levinli303/astroweather-localization/assets/17924287/896cc242-9869-406e-931b-23e0f901fd9b">
<img width="376" alt="Screenshot 2023-07-31 at 22 30 53" src="https://github.com/levinli303/astroweather-localization/assets/17924287/bc964271-1461-4996-addf-86382deaa720">

**Comment by Askaniy** [comment]
Thanks!
Is it too late to add an azimuth reference point setting? The educational standard around me is to count the astronomical azimuth from the south point, and only now I found out that there is another standard

**Comment by levinli303** [comment]
not late at all, added a "Azimuth Zero" setting

<img width="274" alt="Screenshot 2023-08-01 at 08 06 34" src="https://github.com/levinli303/astroweather-localization/assets/17924287/4b2b6770-80d6-4d89-949b-0aa13ffac560">

**Comment by levinli303** [comment]
@Askaniy  i published a beta version here, let me know if Azimuth Zero works as expected https://play.google.com/apps/testing/cc.meowssage.astroweather

**Comment by Askaniy** [comment]
I haven't been able to access, tried several times

**Comment by levinli303** [comment]
@Askaniy  can you try again?

**Comment by Askaniy** [comment]
The application crashes by pressing the sunrise and sunset service button
